# Generated by Django 5.0.7 on 2024-12-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payments_link_payments_session_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payments",
            old_name="link",
            new_name="payment_link",
        ),
    ]
