# Generated by Django 5.0.7 on 2024-12-08 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payments_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_date",
            field=models.DateField(
                default=datetime.date(2024, 12, 8), verbose_name="дата оплаты"
            ),
        ),
    ]
